--------------------------------------------------------------------------------
-- 02_SCHEMA.SQL - CHẠY VỚI ChatApplication
-- Bao gồm: Tables, Indexes, Constraints
--------------------------------------------------------------------------------

-- =============================================================================
-- BẢNG VAI TRÒ (RBAC)
-- =============================================================================
CREATE TABLE VAITRO (
    MAVAITRO    VARCHAR2(20) PRIMARY KEY,
    TENVAITRO   VARCHAR2(100) NOT NULL,
    CHUCNANG    VARCHAR2(500),
    CAPDO       NUMBER DEFAULT 1,
    MOTA        VARCHAR2(500)
) TABLESPACE CHAT_DATA_TS;

-- =============================================================================
-- BẢNG TÀI KHOẢN
-- =============================================================================
CREATE TABLE TAIKHOAN (
    MATK            VARCHAR2(20) PRIMARY KEY,
    TENTK           VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD_HASH   VARCHAR2(256) NOT NULL,
    MAVAITRO        VARCHAR2(20),
    CLEARANCELEVEL  NUMBER DEFAULT 1 NOT NULL CHECK (CLEARANCELEVEL BETWEEN 1 AND 5),
    IS_BANNED_GLOBAL NUMBER(1) DEFAULT 0 CHECK (IS_BANNED_GLOBAL IN (0, 1)),
    IS_OTP_VERIFIED NUMBER(1) DEFAULT 0 CHECK (IS_OTP_VERIFIED IN (0, 1)),
    PROFILE_NAME    VARCHAR2(50) DEFAULT 'CHAT_USER_PROFILE',
    NGAYTAO         TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_LOGIN      TIMESTAMP,
    LAST_LOGOUT     TIMESTAMP,
    LOGIN_COUNT     NUMBER DEFAULT 0,
    PUBLIC_KEY      CLOB,
    FAILED_LOGIN_ATTEMPTS NUMBER DEFAULT 0,
    LOCKED_UNTIL    TIMESTAMP,
    CONSTRAINT FK_TK_VAITRO FOREIGN KEY(MAVAITRO) REFERENCES VAITRO(MAVAITRO)
) TABLESPACE CHAT_DATA_TS;

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_TAIKHOAN_TENTK ON TAIKHOAN(TENTK)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_TAIKHOAN_VAITRO ON TAIKHOAN(MAVAITRO)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =============================================================================
-- BẢNG PHIÊN ĐĂNG NHẬP (Session Management)
-- =============================================================================
CREATE TABLE PHIENDANGNHAP (
    MAPHIEN         VARCHAR2(50) PRIMARY KEY,
    MATK            VARCHAR2(20) NOT NULL,
    IP_ADDRESS      VARCHAR2(50),
    USER_AGENT      VARCHAR2(500),
    THOIDIEM_DANGNHAP TIMESTAMP DEFAULT SYSTIMESTAMP,
    THOIDIEM_HETHAN TIMESTAMP,
    TRANG_THAI      VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (TRANG_THAI IN ('ACTIVE','EXPIRED','LOGGED_OUT')),
    CLEARANCELEVEL_SESSION NUMBER DEFAULT 1,
    CONSTRAINT FK_PHIEN_TK FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK) ON DELETE CASCADE
) TABLESPACE CHAT_DATA_TS;

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_PHIEN_MATK ON PHIENDANGNHAP(MATK)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =============================================================================
-- BẢNG PHÒNG BAN VÀ CHỨC VỤ
-- =============================================================================
CREATE TABLE PHONGBAN (
    MAPB        VARCHAR2(20) PRIMARY KEY,
    TENPB       VARCHAR2(200) NOT NULL,
    MOTA        VARCHAR2(500),
    CLEARANCELEVEL_MIN NUMBER DEFAULT 1
) TABLESPACE CHAT_DATA_TS;

CREATE TABLE CHUCVU (
    MACV        VARCHAR2(20) PRIMARY KEY,
    TENCV       VARCHAR2(100) NOT NULL,
    CAPBAC      NUMBER DEFAULT 1,
    CLEARANCELEVEL_DEFAULT NUMBER DEFAULT 1,
    MOTA        VARCHAR2(500)
) TABLESPACE CHAT_DATA_TS;

-- =============================================================================
-- BẢNG THÔNG TIN NGƯỜI DÙNG
-- =============================================================================
CREATE TABLE NGUOIDUNG (
    MATK        VARCHAR2(20) PRIMARY KEY,
    MAPB        VARCHAR2(20),
    MACV        VARCHAR2(20),
    HOVATEN     VARCHAR2(200),
    EMAIL       VARCHAR2(200),
    SDT         VARCHAR2(20),
    NGAYSINH    DATE,
    DIACHI      VARCHAR2(500),
    AVATAR_URL  VARCHAR2(400),
    BIO         VARCHAR2(1000),
    NGAYCAPNHAT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ND_TK FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK) ON DELETE CASCADE,
    CONSTRAINT FK_ND_PB FOREIGN KEY(MAPB) REFERENCES PHONGBAN(MAPB),
    CONSTRAINT FK_ND_CV FOREIGN KEY(MACV) REFERENCES CHUCVU(MACV)
) TABLESPACE CHAT_DATA_TS;

-- =============================================================================
-- BẢNG LOẠI CUỘC TRÒ CHUYỆN
-- =============================================================================
CREATE TABLE LOAICTC (
    MALOAICTC   VARCHAR2(20) PRIMARY KEY,
    TENLOAICTC  VARCHAR2(200) NOT NULL,
    IS_PRIVATE  VARCHAR2(1) DEFAULT 'N',
    MOTA        VARCHAR2(500)
) TABLESPACE CHAT_DATA_TS;

-- =============================================================================
-- BẢNG CUỘC TRÒ CHUYỆN
-- =============================================================================
CREATE TABLE CUOCTROCHUYEN (
    MACTC               VARCHAR2(60) PRIMARY KEY,
    MALOAICTC           VARCHAR2(20),
    TENCTC              VARCHAR2(200),
    NGAYTAO             TIMESTAMP DEFAULT SYSTIMESTAMP,
    NGUOIQL             VARCHAR2(20),
    IS_PRIVATE          VARCHAR2(1) DEFAULT 'N',
    CREATED_BY          VARCHAR2(20),
    MOTA                VARCHAR2(1000),
    IS_ENCRYPTED        NUMBER(1) DEFAULT 0,
    IS_ARCHIVED         NUMBER(1) DEFAULT 0,
    ARCHIVED_AT         TIMESTAMP,
    MIN_CLEARANCE       NUMBER DEFAULT 1 CHECK (MIN_CLEARANCE BETWEEN 1 AND 5),
    THOIGIANTINNHANCUOI TIMESTAMP,
    CONSTRAINT FK_CTC_LOAI FOREIGN KEY(MALOAICTC) REFERENCES LOAICTC(MALOAICTC),
    CONSTRAINT FK_CTC_QL FOREIGN KEY(NGUOIQL) REFERENCES TAIKHOAN(MATK)
) TABLESPACE CHAT_DATA_TS;

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CTC_NGUOIQL ON CUOCTROCHUYEN(NGUOIQL)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =============================================================================
-- BẢNG PHÂN QUYỀN NHÓM (RBAC cho nhóm chat)
-- =============================================================================
CREATE TABLE PHAN_QUYEN_NHOM (
    MAPHANQUYEN VARCHAR2(20) PRIMARY KEY,
    TENQUYEN    VARCHAR2(100) NOT NULL,
    CAN_ADD     NUMBER(1) DEFAULT 0,
    CAN_REMOVE  NUMBER(1) DEFAULT 0,
    CAN_PROMOTE NUMBER(1) DEFAULT 0,
    CAN_DELETE  NUMBER(1) DEFAULT 0,
    CAN_BAN     NUMBER(1) DEFAULT 0,
    CAN_UNBAN   NUMBER(1) DEFAULT 0,
    CAN_MUTE    NUMBER(1) DEFAULT 0,
    CAN_UNMUTE  NUMBER(1) DEFAULT 0,
    CAN_EDIT    NUMBER(1) DEFAULT 0,
    CAN_PIN     NUMBER(1) DEFAULT 0
) TABLESPACE CHAT_DATA_TS;

-- =============================================================================
-- BẢNG THÀNH VIÊN
-- =============================================================================
CREATE TABLE THANHVIEN (
    MACTC             VARCHAR2(60),
    MATK              VARCHAR2(20),
    NGAYTHAMGIA       TIMESTAMP DEFAULT SYSTIMESTAMP,
    QUYEN             VARCHAR2(100) DEFAULT 'member',
    MAPHANQUYEN       VARCHAR2(20),
    IS_BANNED         NUMBER(1) DEFAULT 0,
    IS_MUTED          NUMBER(1) DEFAULT 0,
    DELETED_BY_MEMBER NUMBER(1) DEFAULT 0,
    NICKNAME          VARCHAR2(100),
    CONSTRAINT PK_THANHVIEN PRIMARY KEY(MACTC, MATK),
    CONSTRAINT FK_TV_CTC FOREIGN KEY(MACTC) REFERENCES CUOCTROCHUYEN(MACTC) ON DELETE CASCADE,
    CONSTRAINT FK_TV_TK FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK) ON DELETE CASCADE,
    CONSTRAINT FK_TV_PQ FOREIGN KEY(MAPHANQUYEN) REFERENCES PHAN_QUYEN_NHOM(MAPHANQUYEN)
) TABLESPACE CHAT_DATA_TS;

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_TV_MATK ON THANHVIEN(MATK)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =============================================================================
-- BẢNG LOẠI TIN NHẮN VÀ TRẠNG THÁI
-- =============================================================================
CREATE TABLE LOAITN (
    MALOAITN    VARCHAR2(20) PRIMARY KEY,
    TENLOAITN   VARCHAR2(100) NOT NULL
) TABLESPACE CHAT_DATA_TS;

CREATE TABLE TRANGTHAI (
    MATRANGTHAI     VARCHAR2(20) PRIMARY KEY,
    TENTRANGTHAI    VARCHAR2(100) NOT NULL
) TABLESPACE CHAT_DATA_TS;

-- =============================================================================
-- BẢNG TIN NHẮN (với SECURITYLABEL cho MAC)
-- =============================================================================
CREATE TABLE TINNHAN (
    MATN            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MACTC           VARCHAR2(60),
    MATK            VARCHAR2(20),
    MALOAITN        VARCHAR2(20),
    MATRANGTHAI     VARCHAR2(20),
    NOIDUNG         CLOB,
    NGAYGUI         TIMESTAMP DEFAULT SYSTIMESTAMP,
    SECURITYLABEL   NUMBER DEFAULT 1 NOT NULL CHECK (SECURITYLABEL BETWEEN 1 AND 5),
    IS_ENCRYPTED    NUMBER(1) DEFAULT 0,
    ENCRYPTED_CONTENT   RAW(2000),
    ENCRYPTED_KEY   CLOB,
    ENCRYPTION_IV   VARCHAR2(100),
    ENCRYPTION_TYPE VARCHAR2(20) DEFAULT 'NONE',
    SIGNATURE       CLOB,
    IS_PINNED       NUMBER(1) DEFAULT 0,
    EDITED_AT       TIMESTAMP,
    CONSTRAINT FK_TN_CTC FOREIGN KEY(MACTC) REFERENCES CUOCTROCHUYEN(MACTC) ON DELETE CASCADE,
    CONSTRAINT FK_TN_TK FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK),
    CONSTRAINT FK_TN_LOAI FOREIGN KEY(MALOAITN) REFERENCES LOAITN(MALOAITN),
    CONSTRAINT FK_TN_TT FOREIGN KEY(MATRANGTHAI) REFERENCES TRANGTHAI(MATRANGTHAI)
) TABLESPACE CHAT_DATA_TS;

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_TN_MACTC ON TINNHAN(MACTC)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_TN_NGAYGUI ON TINNHAN(NGAYGUI)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_TN_SECLABEL ON TINNHAN(SECURITYLABEL)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =============================================================================
-- BẢNG ATTACHMENT
-- =============================================================================
CREATE TABLE ATTACHMENT (
    ATTACH_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MATK        VARCHAR2(20) NOT NULL,
    FILENAME    VARCHAR2(255) NOT NULL,
    MIMETYPE    VARCHAR2(200),
    FILESIZE    NUMBER,
    FILEDATA    BLOB,
    UPLOADED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_ENCRYPTED NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_ATTACH_TK FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK) ON DELETE CASCADE
) TABLESPACE CHAT_DATA_TS;

CREATE TABLE TINNHAN_ATTACH (
    MATN        NUMBER,
    ATTACH_ID   NUMBER,
    CONSTRAINT PK_TN_ATTACH PRIMARY KEY(MATN, ATTACH_ID),
    CONSTRAINT FK_TNA_TN FOREIGN KEY(MATN) REFERENCES TINNHAN(MATN) ON DELETE CASCADE,
    CONSTRAINT FK_TNA_ATT FOREIGN KEY(ATTACH_ID) REFERENCES ATTACHMENT(ATTACH_ID) ON DELETE CASCADE
) TABLESPACE CHAT_DATA_TS;

-- =============================================================================
-- BẢNG XÁC THỰC OTP
-- =============================================================================
CREATE TABLE XACTHUCOTP (
    MAOTP           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MATK            VARCHAR2(20),
    EMAIL           VARCHAR2(200),
    MAXTOTP         VARCHAR2(256),
    THOIGIANTAO     TIMESTAMP DEFAULT SYSTIMESTAMP,
    THOIGIANTONTAI  TIMESTAMP,
    DAXACMINH       NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_OTP_TK FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK) ON DELETE CASCADE
) TABLESPACE CHAT_DATA_TS;

-- =============================================================================
-- BẢNG AUDIT LOGS (Standard Auditing)
-- =============================================================================
CREATE TABLE AUDIT_LOGS (
    LOG_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MATK            VARCHAR2(20),
    ACTION          VARCHAR2(200) NOT NULL,
    TARGET          VARCHAR2(500),
    SECURITYLABEL   NUMBER DEFAULT 0,
    TIMESTAMP       TIMESTAMP DEFAULT SYSTIMESTAMP,
    IP_ADDRESS      VARCHAR2(50),
    DETAILS         CLOB,
    STATUS          VARCHAR2(50) DEFAULT 'SUCCESS',
    OLD_VALUE       CLOB,
    NEW_VALUE       CLOB
) TABLESPACE CHAT_AUDIT_TS;

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_AUDIT_TIME ON AUDIT_LOGS(TIMESTAMP)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_AUDIT_MATK ON AUDIT_LOGS(MATK)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_AUDIT_ACTION ON AUDIT_LOGS(ACTION)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =============================================================================
-- BẢNG QUẢN LÝ POLICY (Admin Panel)
-- =============================================================================
CREATE TABLE ADMIN_POLICY (
    POLICY_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    POLICY_NAME     VARCHAR2(100) NOT NULL UNIQUE,
    POLICY_TYPE     VARCHAR2(50) NOT NULL CHECK (POLICY_TYPE IN ('VPD','FGA','DAC','MAC','RBAC','OLS')),
    TABLE_NAME      VARCHAR2(100) NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    POLICY_FUNCTION VARCHAR2(200),
    STATEMENT_TYPES VARCHAR2(100),
    IS_ENABLED      NUMBER(1) DEFAULT 1,
    CREATED_BY      VARCHAR2(20),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP
) TABLESPACE CHAT_DATA_TS;

CREATE TABLE POLICY_CHANGE_LOG (
    LOG_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    POLICY_ID   NUMBER,
    ACTION      VARCHAR2(50) NOT NULL,
    CHANGED_BY  VARCHAR2(20),
    CHANGED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP,
    OLD_VALUE   CLOB,
    NEW_VALUE   CLOB,
    REASON      VARCHAR2(500)
) TABLESPACE CHAT_AUDIT_TS;

-- =============================================================================
-- BẢNG ENCRYPTION KEYS
-- =============================================================================
CREATE TABLE ENCRYPTION_KEYS (
    KEY_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MATK        VARCHAR2(20),
    KEY_TYPE    VARCHAR2(20) NOT NULL CHECK (KEY_TYPE IN ('RSA_PUBLIC','RSA_PRIVATE','AES','DES')),
    KEY_VALUE   CLOB NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP,
    EXPIRES_AT  TIMESTAMP,
    IS_ACTIVE   NUMBER(1) DEFAULT 1,
    CONSTRAINT FK_EK_TK FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK) ON DELETE CASCADE
) TABLESPACE CHAT_DATA_TS;

COMMIT;
SELECT 'Schema created successfully!' AS STATUS FROM DUAL;
