--------------------------------------------------------------------------------
-- 06_GRANTS.SQL - CHẠY VỚI SYS AS SYSDBA (SAU KHI TẠO SCHEMA VÀ PROCEDURES)
-- File này chạy sau: 02_schema.sql, 03_procedures.sql
-- Gán quyền trên tables và packages cho các roles
--------------------------------------------------------------------------------

-- =============================================================================
-- GRANTS CHO CHAT_ADMIN_ROLE
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ChatApplication.TAIKHOAN TO CHAT_ADMIN_ROLE'; EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Skip TAIKHOAN grant'); END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ChatApplication.NGUOIDUNG TO CHAT_ADMIN_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ChatApplication.CUOCTROCHUYEN TO CHAT_ADMIN_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ChatApplication.THANHVIEN TO CHAT_ADMIN_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ChatApplication.TINNHAN TO CHAT_ADMIN_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT, INSERT ON ChatApplication.AUDIT_LOGS TO CHAT_ADMIN_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT EXECUTE ON ChatApplication.MAC_CTX_PKG TO CHAT_ADMIN_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =============================================================================
-- GRANTS CHO CHAT_USER_ROLE
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON ChatApplication.TAIKHOAN TO CHAT_USER_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE ON ChatApplication.NGUOIDUNG TO CHAT_USER_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON ChatApplication.CUOCTROCHUYEN TO CHAT_USER_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON ChatApplication.THANHVIEN TO CHAT_USER_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT, INSERT ON ChatApplication.TINNHAN TO CHAT_USER_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT EXECUTE ON ChatApplication.MAC_CTX_PKG TO CHAT_USER_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =============================================================================
-- GRANTS CHO CHAT_INTERN_ROLE
-- =============================================================================
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON ChatApplication.TAIKHOAN TO CHAT_INTERN_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON ChatApplication.NGUOIDUNG TO CHAT_INTERN_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON ChatApplication.CUOCTROCHUYEN TO CHAT_INTERN_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT, INSERT ON ChatApplication.TINNHAN TO CHAT_INTERN_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

COMMIT;
SELECT 'Grants completed!' AS STATUS FROM DUAL;
